# Generated by Django 5.1.7 on 2025-03-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Стяг')),
                ('color', models.CharField(choices=[('primary', 'Основной'), ('success', 'Успешный'), ('danger', 'Опасный'), ('warning', 'Тревожный'), ('secondary', 'Второстепенный')], default='primary', max_length=20)),
            ],
            options={
                'verbose_name': 'Стяг',
                'verbose_name_plural': 'Стяги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок исполнения')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Обычный'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('tags', models.ManyToManyField(blank=True, to='tasks.tag', verbose_name='Стяги')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Дела',
                'ordering': ['-due_date'],
            },
        ),
    ]
