# Generated by Django 5.1.4 on 2024-12-27 08:46

import common.utils
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('reg_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Регистрационный номер')),
                ('nic_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Псевдоним')),
                ('image', models.ImageField(blank=True, null=True, upload_to=common.utils.FileUtils.set_correct_file_path, verbose_name='Аватар')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Телефон')),
                ('agreement', models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных')),
                ('subscribe', models.BooleanField(default=False, verbose_name='Подписка на рассылку')),
                ('is_staff', models.BooleanField(default=False, verbose_name='В команде')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['-is_staff', '-is_active', 'last_name', 'first_name', 'middle_name'],
            },
        ),
    ]
